### ISSUE TITLE
Settings bugs and open issues

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/DexEx#16]
We should align this text (EN - USD)
<img width="447" alt="screen shot 2018-10-19 at 15 36 09" src="https://user-images.githubusercontent.com/10923247/47221483-c192d680-d3b4-11e8-9570-de0d7a57312a.png">

Order Time to live should show "Day" instead of the 3 dots
<img width="452" alt="screen shot 2018-10-19 at 15 35 53" src="https://user-images.githubusercontent.com/10923247/47221516-d96a5a80-d3b4-11e8-8dc1-0ff9f0cc637b.png">

I am not entirely sure that this should be visible to users
<img width="450" alt="screen shot 2018-10-19 at 15 35 33" src="https://user-images.githubusercontent.com/10923247/47221531-e71fe000-d3b4-11e8-8a61-42e1b00082ce.png">

**Comment by aesthytik** [comment]
Done PR https://github.com/dexlab-io/DexEx/pull/36  @dimarconicola 

The text is aligned center!
![screenshot 2018-11-10 at 18 26 31](https://user-images.githubusercontent.com/26917061/48301589-57360780-e516-11e8-8633-d98a58571abc.png)

The day, month etc are fuly visible
![screenshot 2018-11-10 at 18 26 43](https://user-images.githubusercontent.com/26917061/48301599-7896f380-e516-11e8-82c0-9c7bc7898eb2.png)
