### ISSUE TITLE
Market Tab - Market Tab stays open after selecting a pairs

### ISSUE THREAD

**Issue by alearrigo** [dexlab-io/DexEx#29]
After selecting a pair, the market tab should close automatically and redirect the user to the new market. The tab stays open instead.

EDIT: why are there two scroll bars? 

![market 1-2](https://user-images.githubusercontent.com/33393095/47510340-429c1300-d878-11e8-96d0-e6a059467be5.png)

**Comment by aesthytik** [comment]
@alearrigo the second scrollbar comes when we use inspect element to view the HTML.
