### ISSUE TITLE
P2P Trade - Text Padding

### ISSUE THREAD

**Issue by alearrigo** [dexlab-io/DexEx#31]
Text is outside the inputbox

![p2p trade 1](https://user-images.githubusercontent.com/33393095/47510909-63b13380-d879-11e8-8acc-4db8c4d56fa2.png)

**Comment by aesthytik** [comment]
@alearrigo can you please tell me your OS and browser u used. And how can i regenerate the issue? Because its looking good on my system.

**Comment by alearrigo** [comment]
@aesthytik 
Google Chrome 70.0.3538.77 on Win10.
When I select the box to choose the token, I have the possibility to write as well, to find it faster. If I write, the text is out of the box as in the image above.

**Comment by aesthytik** [comment]
@alearrigo great thanks!
