### ISSUE TITLE
Order Form, input area goes over the label

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/DexEx#5]
<img width="254" alt="screen shot 2018-10-19 at 14 44 47" src="https://user-images.githubusercontent.com/10923247/47218918-9eb0f400-d3ad-11e8-9c11-a4cc632d85d5.png">

**Comment by aesthytik** [comment]
Done PR https://github.com/dexlab-io/DexEx/pull/39

**Comment by dimarconicola** [comment]
@aesthytik can you please attach a screenshot of this?

**Comment by aesthytik** [comment]
![screenshot 2018-11-10 at 17 59 46](https://user-images.githubusercontent.com/26917061/48301354-89456a80-e512-11e8-9c35-c1dc09871f8c.png)
Here it is @dimarconicola
