### ISSUE TITLE
Sell form has a button saying "buy max"

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/DexEx#8]
<img width="255" alt="screen shot 2018-10-19 at 14 50 51" src="https://user-images.githubusercontent.com/10923247/47219191-707fe400-d3ae-11e8-91be-70c1d74d00ae.png">

**Comment by aesthytik** [comment]
@dimarconicola can you please tell what should be in its place.

**Comment by aesthytik** [comment]
or should we remove it

**Comment by dimarconicola** [comment]
"sell max"

**Comment by aesthytik** [comment]
thanks

**Comment by aesthytik** [comment]
DONE PR https://github.com/dexlab-io/DexEx/pull/40
