### ISSUE TITLE
After using suggestions on inputs, it turns yellow

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/DexEx#9]
1. this is the suggestion
<img width="239" alt="screen shot 2018-10-19 at 14 52 09" src="https://user-images.githubusercontent.com/10923247/47219273-acb34480-d3ae-11e8-91d5-3cac73d89db1.png">

2. this is when selecting
<img width="241" alt="screen shot 2018-10-19 at 14 52 17" src="https://user-images.githubusercontent.com/10923247/47219286-b6d54300-d3ae-11e8-8b0c-f982ef65942d.png">

3. this is after being selected
<img width="232" alt="screen shot 2018-10-19 at 14 52 22" src="https://user-images.githubusercontent.com/10923247/47219297-bdfc5100-d3ae-11e8-8c5a-040d6d4dde8e.png">

**Comment by aesthytik** [comment]
when selecting:-
![screenshot 2018-11-10 at 18 16 01](https://user-images.githubusercontent.com/26917061/48301472-c579ca80-e514-11e8-963b-f9a20a21700a.png)

After selected:-
![screenshot 2018-11-10 at 18 16 13](https://user-images.githubusercontent.com/26917061/48301479-d296b980-e514-11e8-948d-80c7842c1b8d.png)

@dimarconicola

**Comment by aesthytik** [comment]
PR here https://github.com/dexlab-io/DexEx/pull/37
